apiVersion: v1
kind: Pod
metadata:
  name: POD-C
spec:
  containers:
  - name: POD-C
    image: POD-C:latest
    ports:
      - name: tcp
        protocol: TCP
        containerPort: 80
    resources:
      requests:
        memory: "400Mi"
      limits:
        memory: "400Mi"